spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: polska13
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8087

