spring:
  datasource:
    url: jdbc:mysql://database:3306/credit?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
endpoints:
  product: http://localhost:8087/api/products
  customer: http://localhost:8088/api/customers

